// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoo8g_h1puk42YUrQ3GjxvFbcXj4AhOTQ',
    appId: '1:139517536307:web:4f54daac2d58be3b4e5b46',
    messagingSenderId: '139517536307',
    projectId: 'login-signup-auth-8d122',
    authDomain: 'login-signup-auth-8d122.firebaseapp.com',
    storageBucket: 'login-signup-auth-8d122.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgR9uoDlSPeYxaZLsQzDB91oH0coRZ4Rk',
    appId: '1:139517536307:android:cf63371150ce42e84e5b46',
    messagingSenderId: '139517536307',
    projectId: 'login-signup-auth-8d122',
    storageBucket: 'login-signup-auth-8d122.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbkele18ak9Dt2kg7078i_OzqSFv2G7U4',
    appId: '1:139517536307:ios:2a254195f47838c54e5b46',
    messagingSenderId: '139517536307',
    projectId: 'login-signup-auth-8d122',
    storageBucket: 'login-signup-auth-8d122.appspot.com',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbkele18ak9Dt2kg7078i_OzqSFv2G7U4',
    appId: '1:139517536307:ios:2a254195f47838c54e5b46',
    messagingSenderId: '139517536307',
    projectId: 'login-signup-auth-8d122',
    storageBucket: 'login-signup-auth-8d122.appspot.com',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );
}
